### ISSUE TITLE
cors problem when querying over jsonld file with vc

### ISSUE THREAD

**Issue by elsdvlee** [SolidLabResearch/generic-data-viewer-react-admin#131]
No results for queries over jsonld resources with VC. 
![image](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/93709574/17a33953-aac2-4e12-a9fb-78c705161c88)

**Comment by mvanbrab** [comment]
Explanation of the CORS problem:
- when we load a .jsonld file
- and that .jsonld file results in the browser loading a context file
- and the server serving does not provide an appropriate CORS header (w3.org!)
- then we get this error!

But...
- we are requesting ntriples to the Solid server
- in which case the Solid server translates the .jsonld file to ntriples
- and avoid the CORS problem

So... what's happening here? Maybe some extra testcase info will help.

**Comment by mvanbrab** [comment]
This happens on the <https://pod.playground.solidlab.be/>, logged in as `user1@pod.playground.solidlab.be`:

![image](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/a7025c10-2111-4da6-a88d-7023169ea5ab)

(The Accept header in the request is as intended)

**Comment by mvanbrab** [comment]
Info: same exercise on <https://css11.onto-deside.ilabt.imec.be> works.
Is this an issue of the playground?

**Comment by bjdmeest** [comment]
> This happens on the https://pod.playground.solidlab.be/, logged in as `user1@pod.playground.solidlab.be`:
> 
> ![image](https://private-user-images.githubusercontent.com/6448245/340752563-a7025c10-2111-4da6-a88d-7023169ea5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NzgyMTIsIm5iZiI6MTcxODc3NzkxMiwicGF0aCI6Ii82NDQ4MjQ1LzM0MDc1MjU2My1hNzAyNWMxMC0yMTExLTRkYTYtYTg4ZC03MDIzMTY5ZWE1YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMDYxODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE3ZTA0OWNlZTBiOWVkNDZhMWMzNmRjMzczYjY5MDU5ZDYxOGJiOGU2N2ZjOWE3ZjMxODQ3ZDQzMTZkNDk5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.81sj51kZmUAT_8gBTvgwNQcLCcFPpokQD5BPyF0y0ms)
> 
> (The Accept header in the request is as intended)

What's the actual result when you're logged in? nquads or jsonld? Maybe the playground for some reason can't handle graphs?

**Comment by mvanbrab** [comment]
On the Solid Playground, the returned content type is `application/ld+json`.
On our CSS it is `application/n-quads`.
Same code calling in both cases, same request headers etc...

Many details in illustrations below.

Questions:
- **why does the Solid Playground behave like this?**
-  **do we have to work around this from our side to be safe for portability to other Solid servers?**

## When logged in to CSS

### Overview

![CSS11](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/e13c377b-2603-4d5d-a27b-e0158ea1ec3f)

### Headers on the GET of products

![CSS11_GET_products](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/d826d184-8ff1-4397-b7c0-8fcc5987f4b4)

## When logged in to Solid Playground:

### Overview

![SolidPlayground](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/f1503d09-c94f-4d7a-8ab6-6759940c3b92)

### Headers on the GET of products

![SolidPlayground_GET_products](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/90f1eb88-3123-4917-93f4-cfca595af647)

**Comment by bjdmeest** [comment]
The only thing I can think of is that the playground for some reason doesn't support quads, and you could try accept: text/turtle before jsonld to see whether that solves it. turtle is a MUST for LDP, so we should at least assume every server can handle that one

**Comment by mvanbrab** [comment]
More observations:
```javascript
// original (goes wrong, returns application/ld+json)
Accept: "application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,*/*;q=0.1"
// original modified: delta between q factors 0.1 (works, returns application/n-quads)
Accept: "application/n-quads,application/trig;q=0.9,application/ld+json;q=0.8,application/n-triples;q=0.7,*/*;q=0.1"
// original modified: delta between q factors 0.1 and replaced application/ld+json with text/turtle (works, returns application/n-quads)
Accept: "application/n-quads,application/trig;q=0.9,text/turtle;q=0.8,application/n-triples;q=0.6,*/*;q=0.1"
```

The problem is that in contrast with the CSS's (v7.0.2) on `https://....onto-deside.ilabt.imec.be/`, the CSS in the Solid Playground <https://pod.playground.solidlab.be/> (v7.x.x) does not follow q factor priorities as expected with the q values in the original Accept header we were using.
This seems solved by changing the q factors so that they differ at least 0.1, see the second Accept header above.
I filed [an issue](https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1920) for that in the CSS repo.

Finally, for the viewer I'll use the third Accept header, to be sure: we don't wont `application/ld+json` at all.
