### ISSUE TITLE
Allow to add custom query + editor

### ISSUE THREAD

**Issue by bjdmeest** [SolidLabResearch/generic-data-viewer-react-admin#54]
example: https://query.linkeddatafragments.org/

And be able to store it in your pod

**Comment by bjdmeest** [comment]
'and be able to store it in your pod' is optional in a first version

**Comment by mvanbrab** [comment]
Maybe linked to #32?

**Comment by mvanbrab** [comment]
While discussing with @EmilioTR 
- Simplify: do not put the result in a pod.
- Make a dialogue or dialogues with fields corresponding to all possible entries in the config file, and execute the result of combining all these fields. The query field can be inspired on <https://query.linkeddatafragments.org/> (github repo indicated above by @bjdmeest). 
- Let's not consider persisting the resulting query fot the moment, but perhaps provide some kind of export to a portion of a config file.
