### ISSUE TITLE
Logout has no effect on query results

### ISSUE THREAD

**Issue by mvanbrab** [SolidLabResearch/generic-data-viewer-react-admin#63]
After logging out, the app behaves as if the last logged in user is still logged in.
Test: execute query "A list of my favorite books"
(a) not logged in --> no result (OK)
(b) logged in --> result (OK)
(c) logged out --> result (not OK, should have been no result)

**Comment by bjdmeest** [comment]
todo: on logout: myEngine.invalidateCache()
