### ISSUE TITLE
Add 'verify' checkmark per source, that when clicked executes a timeout function taking the authenticated fetch and source url as input

### ISSUE THREAD

**Issue by bjdmeest** [SolidLabResearch/generic-data-viewer-react-admin#73]

**Comment by mvanbrab** [comment]
Suggestion:
- execute the verification code after the normal fetch of the source (function to be given, will include a fetch to an additional resource)
- add an entry to the query configuration in the config file, indicating whether verification is wanted or not.

@bjdmeest This is in contradition with the literal title where you suggest verification is only done after clicking an extra button. If you have good reasons for your suggestions, please feedback here.

**Comment by bjdmeest** [comment]
only reason to do it later, is for performance: verification will not always be needed, but if there are good reasons to do it in a first version right after the query: go ahead! we can always optimize later

**Comment by mvanbrab** [comment]
Oh yes, good reason! It also makes the configuration setting unnecessary. So @axellorreyne, choose @bjdmeest 's suggestion unless it is technically too complicated.

**Comment by mvanbrab** [comment]
Final status: provided in framework, with stub code. Create new issue to integrate actual verification code.
