### ISSUE TITLE
values for query parameters as result of query (aka "Indirect variables in templated query")

### ISSUE THREAD

**Issue by elsdvlee** [SolidLabResearch/generic-data-viewer-react-admin#78]
Now we can set add a list of values to the config file, to use as parameters in templated queries. 
To secure scalability it would be better to have to option to configure this list of values as the result of a query.

**Comment by elsdvlee** [comment]
Additionally, make the value list a searchable dropdown. See https://marmelab.com/react-admin/AutocompleteInput.html

**Comment by mvanbrab** [comment]
Additional input:
- This query should work on the same source(s) as the main query (no need to provide an individual set of sources; will require Comunica context `{"lenient": true}`
- Support for this feature to be added to the custom query form too

**Comment by mvanbrab** [comment]
In addition to the "searchable dropdown", consider a free text input.
