### ISSUE TITLE
Loaded label above table only counts results of the page

### ISSUE THREAD

**Issue by bjdmeest** [SolidLabResearch/generic-data-viewer-react-admin#83]
The 'Loaded: 10 results' label above the table in the viewer only counts the results of the page, not the total result. It is confusing as the actual table has more results.

**Comment by mvanbrab** [comment]
True! And the count can be seen at the bottom right of the displayed table anyway:
"Rows per page: 10       1-10 of 66".
Better remove the display of "Loaded ...".
